### ISSUE TITLE
Is `Test.re` working?

### ISSUE THREAD

**Issue by jchavarri** [ahrefs/melange-react-intl#16]
I see the dune file in the test consumes the ppx as a library:

https://github.com/ahrefs/melange-react-intl-ppx/blob/b8833abfd8601bc687aa0d299232e2742ac2a9fa/test/dune#L4

but it should use something like `(preprocess (pps melange-react-intl-ppx))`?

cc @ixzzd @schinns

**Comment by schinns** [comment]
Yes, testing needs to be improved. I can take this on. @davesnx had suggested adding test similar to styled-ppx test:
https://github.com/davesnx/styled-ppx/blob/main/packages/ppx/test/css-support/dune#L25

**Comment by davesnx** [comment]
Test.re isn't used rather than running it manually, now that we have ppx snapshot testing no need for it IMO.

**Comment by ixzzd** [comment]
Since [we can run cram tests in the watch mode](https://github.com/ahrefs/melange-react-intl/pull/25/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R55-R56) I don't think we still need `Test.re`, lets get rid of it. I will add a PR

**Comment by jchavarri** [comment]
Ftr the `Test.re` is being build by a `melange.emit` stanza in the same folder, that was added in https://github.com/ahrefs/melange-react-intl/pull/18. I think it's useful to test that the generated code by the PPX is valid Melange code, and can be built by the compiler.

(Side note: `library` stanzas of private libraries don't get built by default because they're not added to the `default` alias, but `melange.emit` stanzas do).

**Comment by davesnx** [comment]
It's very useful to keep melange compilation running while developing the ppx (probably the name isn't the best and lacks a comment explaining this) but Test.re is useful
